<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_579ae865e35f0',
	'title' => 'Additional Fields',
	'fields' => array (
		array (
			'key' => 'field_579aef03d7ff4',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'google_map',
			'instructions' => 'We will use your address to find those around you.	We will not share your address with any other GardenHui members.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array (
			'key' => 'field_579ae8958b0db',
			'label' => 'I\'m interested in...',
			'name' => 'role',
			'type' => 'checkbox',
			'instructions' => 'Check all that apply',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'grower' => 'Finding a garden',
				'owner' =>  'Hosting a garden',
				'farmer' => 'Helping with gleaming/farm days',
				'mentee' => 'Finding a mentor',
				'mentor' => 'Becoming a mentor',
				'sharer' => 'Sharing food I\'ve grown'
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
		array (
			'key' => 'field_57a181a859c7b',
			'label' => 'Skills',
			'name' => 'skills',
			'type' => 'text',
			'instructions' => 'List skills that you are proficient in so other gardenhui members can connect with you!',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'gardening, mulching, composting...',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57a181c059c7d',
			'label' => 'Resources',
			'name' => 'resources',
			'type' => 'text',
			'instructions' => 'List any tools or resources that you\'d like to share with your Hui.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'garden hoes, gloves, etc...',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57b7f1dc26408',
			'label' => 'Show my real name',
			'name' => 'private_profile',
			'type' => 'true_false',
			'instructions' => 'If left unchecked, your username will be shown on public pages.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'user_role',
				'operator' => '==',
				'value' => 'all',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'custom_fields',
		4 => 'discussion',
		5 => 'comments',
		6 => 'revisions',
		7 => 'slug',
		8 => 'author',
		9 => 'format',
		10 => 'page_attributes',
		11 => 'featured_image',
		12 => 'categories',
		13 => 'tags',
		14 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;

?>
